package com.example.junit_selenium;

// Generated by Selenium IDE
import java.util.concurrent.TimeUnit;

import com.codeborne.selenide.Configuration;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;

public class SearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        //driver = new FirefoxDriver();


        Configuration.startMaximized =true;
        open("about:blank");
        driver = getWebDriver();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void google() {
        driver.get("https://www.google.es/");
        driver.manage().window().setSize(new Dimension(1107, 1000));
        driver.switchTo().frame(0);
        driver.findElement(By.cssSelector("#introAgreeButton .RveJvd")).click();
        driver.switchTo().defaultContent();
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("devops");
        try{
            TimeUnit.SECONDS.sleep(3);
        }catch (InterruptedException e){
            //handle the exception
        }
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);

    }
}